// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Sales.Core.Core;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Sales.Infraestructure.Entities;

public partial class Negocio : PersonBase
{
    [Key]
    public int NegocioId { get; set; }

    public string UrlLogo { get; set; }

    public string NombreLogo { get; set; }

    public string NumeroDocumento { get; set; }

    public decimal? PorcentajeImpuesto { get; set; }

    public string SimboloMoneda { get; set; }

}